cfpb/django-flags

- mkdocs.yml
PyMdown Extensions deprecated the GitHub extension. Replace it with the extensions that it included that we're most interested in.
This should fix the daily build of master.
> Remove deprecated github markdown extension

- flags/forms.py
- flags/tests/test_forms.py
Previously, the FlagStateForm condition choices were bound
when the module was loaded. It is possible for this happen
before custom conditions in other Django apps have been
registered.
This commit delays populating the choices until the form is
created. This allows all custom conditions to be registered
first.
> Bind condition choices when admin form is created

- docs/api/jinja2.md
- flags/template_functions.py
- flags/templatetags/feature_flags.py
- flags/tests/test_forms.py
- flags/tests/test_template_functions.py
- flags/tests/test_templatetags_feature_flags.py
- flags/urls.py
This PR makes a slight change to both Django and Jinja2 template tags/functions to make the `request` optional. In Django templates, `request` will not be assumed to be in the `context`, and in Jinja2 templates, the `request` argument is now optional.
Some conditions still require the `request` to be evaluated, but those conditions will raise `RequiredForCondition` if it is not given.
This PR also bumps the version to 3.0.1 in anticipation of release once it's merged.
This should close https://github.com/cfpb/wagtail-flags/issues/30
> Make requests optional in template tags

- flags/conditions.py
- flags/tests/test_conditions.py
Previously, `user_condition` was assuming that the default
User model was being used. This causes an error in projects
using custom user models.
Instead of taking the hit of loading the user record from
the database again within the condition, we should be able
to just compare the provided username against the user
instance that is already attached to the request.
Both the `AbstractBaseUser` and `AnonymousUser` implement a
`get_username()` function so it should be safe to rely on
that.
> Allow user_condition to work with custom user models

- .travis.yml
- docs/api/state.md
- docs/index.md
- flags/middleware.py
- flags/state.py
- flags/tests/test_middleware.py
- flags/tests/test_state.py
- setup.py
- tox.ini
This should allow us to use the same flag conditions throughout a single request cycle without querying the database more than once per flag. It only affects flag checks that happen during a request cycle and then only when the middleware is enabled and the request is provided as a keyword argument for the flag check (which happens automatically with the context preprocessors configured as the documentation recommends).
This is an alternative, less heavy-handed approach to the same problem that #9 attempts to address. This PR and #9 should be seen as mutually exclusive. 
This change doesn't provide quite as large a performance improvement, and still requires optional configuration to take advantage of (adding the middleware to `MIDDLEWARE`), but it does allow us to start addressing the …
> Add middleware to attach flag conditions to the request

- flags/sources.py
- flags/tests/test_sources.py
- setup.py
This PR fixes a bug where a TypeError can be raised if a condition function is not registered for a condition name that a flag attempts to check.
Prior to this change the following would raise a TypeError:
```python
condition = Condition('my_condition', 'value')
condition.check()
```
If there is not a corresponding `condition.register('my_condition', fn=my_condition_function)`.
After this change, `condition.check()` will return None, which is Falsy.
> Fix a TypeError when a configured condition has no function registered

- flags/apps.py
- flags/checks.py
- flags/sources.py
- flags/tests/test_checks.py
- flags/tests/test_sources.py
- setup.py
This PR moves the logging introduced in #15 to a system check at startup time.
This looks like:
```
Performing system checks...
System check identified some issues:
WARNINGS:
?: (flags.E001) Flag TEST_FLAG has non-existent condition "site"
HINT: Register "site" as a Django-Flags condition.
System check identified 1 issue (0 silenced).
```
> Move logging of non-existent conditions to a system check

- docs/api/sources.md
- flags/checks.py
- flags/sources.py
- flags/tests/test_sources.py
This change adds an option to `get_flags` to ignore any errors that occur when getting flags from a flag source. The `ignore_errors` option is `False` by default.
This allows the `DatabaseFlagsSource` to raise an `OperationalError` or `ProgrammingError` when running the system check before migrations have been applied without causing any issues.
`ignore_errors` is now used in the flag conditions system check so the check won't error when migrations have not yet been run.
Fixes #18 and closes #17.
> Optionally catch exceptions in flag sources

- docs/css/overrides.css
- docs/theme-overrides/toc.html
- mkdocs.yml
This PR updates the overrides for the MkDocs ReadTheDocs theme from the [cfpb/cfgov-refresh docs](https://github.com/cfpb/cfgov-refresh/tree/master/docs).
> Update RTD MkDocs theme overrides from cfgov-refresh

- docs/conditions.md
- flags/conditions.py
- flags/tests/test_conditions.py
This PR adds a new `before date` condition that simply enables a flag if the current date is *before* the given date. This is the inverse of the existing `after date` condition.
> Add a "before date" condition

- docs/conditions.md
- flags/conditions.py
- flags/tests/test_conditions.py
This PR makes small changes to the boolean and parameter conditions:
Boolean conditions can now match strings with superfluous whitespace around their values, so if, for example, `'  true  '` is entered as the value of the boolean condition, it will evaluate to `True`. Previously it did not.
Parameter conditions previously checked for `True` explicitly as the value of the parameter, i.e. `?my_flag=True`. This means other possible variations, `?my_flag=true`, `?my_flag=yesplease`, and just `?my_flag` would not work. [The documentation is ambiguous on the expected behavior of parameter conditions](https://cfpb.github.io/django-flags/conditions/#parameter), but the original intent was probably that any variation above would work. This PR clarifies the documentation and changes the …
> Fix boolean and parameter conditions

- .travis.yml
- flags/tests/settings.py
- setup.py
- tox.ini
[Django 2.2 was just released](https://docs.djangoproject.com/en/2.2/releases/2.2/) and is a new LTS release, which is unfortunately hard to install with `django-flags` being pinned to `'Django>=1.11,<2.2'`
This PR:
* Enables tests for Python 3.7 in Tox and Travis
* Enables tests for Django 2.2 in Tox and Travis
* Updates flags.tests.settings to be compatible with the Django 2.1+ checks regarding the admin's dependency on the messages app
* Updates Travis CI to use a version of Ubuntu which has Python 3.7 packages
> Django 2.2 support

- docs/api/urls.md
- docs/api/views.md
- docs/conditions.md
- flags/tests/test_views.py
- flags/views.py
- mkdocs.yml
This PR adds documentation for the `FlaggedViewMixin` and `FlaggedTemplateView` classes that provide options for flagging class-based views.
It also deprecates the `condition` attribute on `FlaggedViewMixin`. The term "condition" has come to mean the thing that evaluates the state of the flag, rather than the expected evaluation. Using `condition` will not warn about its deprecation and recommend using `state` instead. This is now consistent with the use of the terms `condition` and `state` elsewhere in the Django-Flags API.
It also changes all our links to the Django 2.x docs to upcoming LTS release 2.2.
This PR will close #29.
> Document the flagged-class-based view API

- docs/api/decorators.md
- docs/api/urls.md
- docs/api/views.md
- mkdocs.yml
Fallback views must take the same arguments and keyword arguments as the corresponding flagged view. This change adds that explicitly to the docs in all the places where the option exists to provide a fallback.
These admonitions look like:
> Add notes to the docs about fallback view arguments

- docs/api/sources.md
- docs/api/urls.md
- docs/conditions.md
- docs/index.md
- docs/settings.md
- docs/usage.md
The link at the bottom of [the Conditions documentation page](https://cfpb.github.io/django-flags/conditions/) is currently broken and doesn't work when the documentation isn't hosted at the root of the domain.
This commit fixes the link.
> Fix link to conditions API

- README.md
Closes #43. We never updated the supported versions of Django in the README when we dropped support for Django 1.8 in 4.0.0. This PR fixes that.
> Fix supported versions of Django in README

- docs/api/state.md
- docs/api/urls.md
- flags/decorators.py
- flags/state.py
- flags/tests/test_decorators.py
- flags/tests/test_state.py
- flags/tests/test_views.py
- flags/views.py
This PR is intended to better communicate to users of Django-Flags various expectations and assumptions that get made but that aren't always obvious (even to me). These include:
- That feature flag state can't be checked before the app registry is ready
- That flag state can't be checked at import-time of modules that Django loads when starting up (like urls.py)
- FlaggedViewMixin now constructs its decorated view at `as_view()` call time rather than at request time. This should ensure that any errors are reported at start-up rather than in a request cycle.
- Fallback functions that do not take the same arguments as their corresponding flagged functions will now raise a `RuntimeWarning`. Along with #38, this closes #37.
> Provide clarity around when feature flag state can be checked

- docs/settings.md
- flags/sources.py
- flags/tests/test_sources.py
This PR adds `INFO`-level logging to flag state checking when flag state is True with the conditions that were met. This depends on a new setting, `FLAGS_STATE_LOGGING`, which defaults to `True`.
The logging looks like this:
```
INFO:flags.sources:Flag MY_FLAG evaluated False with conditions: boolean (False).
INFO:flags.sources:Flag MY_FLAG evaluated True with conditions: boolean (False), path matches (True).
```
This should help track the history and usage of flags, without depending on the particularities of conditions (i.e. we don't record when a 'boolean' condition is set to `True`, instead we record when checks are made that end with the flag state being `True`).
> Add logging to flag state checking

- flags/templatetags/flags_debug.py
- flags/tests/test_templatetags_flags_debug.py
This change will say 'MYFLAG is disabled for all requests, even when all required conditions are met.' when there are required conditions along with a non-required boolean condition and no other non-required conditions.
This is a change from 'MYFLAG is disabled when all required conditions are met.' which is somewhat confusing.
This change also refactors the string creation somewhat to reduce the duplication of strings. Hopefully the way I'm slicing makes eventual translation doable... but I'm not entirely sure that'll be the case.
With the [Flag conditions Debug Toolbar panel](https://cfpb.github.io/django-flags/debugging/#flag-conditions) this looks like:
With https://github.com/cfpb/wagtail-flags/pull/35 this looks like:
> Use clearer language for booleans with required conditions

- flags/sources.py
- flags/tests/test_sources.py
755a11290c70f7048f479525a5593d3554cc0ae7 did some refactoring of when optional and required conditions are filtered. This has resulted in some issues where conditions aren't being correctly evaluated. 
Thanks to @chosak, the issue is [`conditions` is modified on the `Flag` object after `__init__` is called](https://github.com/cfpb/django-flags/blob/3481867933e1dc84e7cbddf53954c80ac8af0898/flags/sources.py#L186), but `optional_conditions` and `required_conditions` are never updated after `__init__`. 
This seems like it was a false optimization. This PR reverts it to fix the issue.
> Move optional/required condition filtering back to check_state()

- flags/sources.py
- flags/templates/flags/panels/flags.html
- flags/templatetags/flags_debug.py
- flags/tests/test_templatetags_flags_debug.py
"Optional" does not seem like the right word to use in retrospect. The difference between required and non-required conditions is the difference between a boolean AND and a boolean OR. So, no condition is "optional" — at least one of them has to be met.
This change removes the word "optional" from the state string when there are no required conditions, and replaces it with "non-required" when there are.
It also removes "optional" from the code in places where we refer to conditions that are not required.
> Remove "optional" from state string language

- README.md
This is a simple change following #52 to change the badge in the README from Travis to GitHub Actions.
> Update tests badge in README to GitHub Actions

- docs/conditions.md
I was looking at the docs and couldn't tell how the `anonymous` condition differed from the `boolean` condition. Looking at the source, it seems to be about whether the user is logged into Django or not. Do I have that right?
> Clarify docs for anonymous condition

- .github/workflows/test.yml
- README.md
This PR removes the separate Coverage job in our tests action, puts coveralls submission in the unit test steps, and renames the jobs to be consistently cased with other non-GitHub Actions checks.
This, and deleting django-flags from Coveralls and re-adding it, seems to fix the coverage reporting.
> Fix Coveralls with GitHub Acitons

- flags/sources.py
- flags/tests/test_conditions.py
- flags/tests/test_models.py
- flags/tests/test_sources.py
- flags/tests/test_urls.py
- flags/tests/test_views.py
- pyproject.toml
This follows on from #56. Our [development standards](https://github.com/cfpb/development/blob/master/standards/python.md#linting) refer to PEP8 for line length. This change fixes an error that specified lines be 78 instead of 79 for black.
> Use our PEP8-specified line length

- .github/workflows/test.yml
- flags/tests/test_panels.py
- setup.py
- tox.ini
This change adds support for Django 3.0. It requires updating the Django Rest Framework supported version range and dealing with the minor API changes that it brings with it.
This change also drops testing for non-LTS versions of Django 2.0. Those versions should be supported, but if you're using Django 2.x you should be on 2.2.
> Add support for Django 3.0

- setup.py
#58 (f4007d5) relies on [an interface change](https://github.com/jazzband/django-debug-toolbar/commit/5299cf826284b6e082c5f18050e4f706faa81c39#diff-0caf32ffe5d678b291e3873eac4db0c6R21) in django-debug-toolbar that was introduced in version 2.0. Running the tests against previous version 1.11 fails because of this.
> Remove unsupported django-debug-toolbar version

- .github/workflows/test.yml
- docs/api/urls.md
- docs/api/views.md
- docs/index.md
- docs/releasenotes.md
- docs/usage.md
- flags/conditions/conditions.py
- flags/sources.py
- flags/templatetags/feature_flags.py
- flags/tests/settings.py
- flags/tests/test_admin.py
- flags/tests/test_decorators.py
- flags/tests/test_sources.py
- flags/tests/test_state.py
- flags/tests/test_urls.py
- flags/urls.py
- setup.py
- tox.ini
This PR does some cleanup for our 5.0.0 release. This includes removing Django 1.11 support and removing support for single-dictionary key/value flag definitions in settings that was deprecated in 4.1. I've also removed the dependency on `mock` in favor of `unittest.mock`.
> Remove Django 1.11 support and cleanup for 5.0.0 release

- flags/jinja2tags.py
- flags/panels.py
- flags/state.py
- flags/tests/test_panels.py
- setup.py
- tox.ini
Removed `not_skip` and `recursive` from `tox.ini` to fix
TypeError: __init__() got an unexpected keyword argument 'not_skip'
Prior to version 5.0.0, isort wouldn't automatically traverse directories. The --recursive option was necessary to tell it to do so. In 5.0.0 directories are automatically traversed for all Python files, and as such this option is no longer necessary and should simply be removed.
In an earlier version isort had a default skip of __init__.py. To get around that many projects wanted a way to not skip __init__.py or any other files that were automatically skipped in the future by isort. isort no longer has any default skips, so if the value here is __init__.py you can simply remove the setting.
https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/
Short …
> Updates to support isort 5.0

- .github/workflows/test.yml
- README.md
- setup.py
- tox.ini
This PR adds support for testing against Django 3.1 and updates the README and `setup.py` to include Django 3.1 in the supported version range.
> Add support for Django 3.1

- README.md
- docs/api/state.md
- docs/management_commands.md
- docs/releasenotes.md
- flags/management/commands/disable_flag.py
- flags/management/commands/enable_flag.py
- flags/panels.py
- flags/state.py
- flags/tests/test_management_commands_disable_flag.py
- flags/tests/test_management_commands_enable_flag.py
- flags/tests/test_state.py
- mkdocs.yml
This change adds two flag state functions, `enable_flag` and `disable_flag`, that will either add or modify an existing boolean condition to either enable or disable a flag.
It also adds an `enable_flag` and `disable_flag` management commands which call those functions. This will enable easier enabling/disabling of a flag through automations, etc.
If a flag has required conditions, those will take precedence over the boolean that's added/modified.
> Add API and management commands for enabling/disabling flags

- docs/releasenotes.md
- flags/conditions/__init__.py
- flags/conditions/conditions.py
- flags/conditions/validators.py
- flags/tests/test_conditions_validators.py
- tox.ini
Because "path matches" conditions can be any valid regular expression, this change simply uses `re.compile()` to validate them.
Previously they were validated as URL paths, without querystring or URL scheme-matching characters allowed. This warned on some valid regular expressions that it shouldn't have.
This fix is what @chosak suggested in, and fixes #77.
> Validate "path matches" conditions as regular expressions

- .github/workflows/test.yml
- README.md
- docs/releasenotes.md
- flags/state.py
- flags/tests/test_conditions_validators.py
- setup.py
- tox.ini
This PR brings in @gregtap's changes from #87, makes sure the tests pass, and updates our preferred Python to test against to 3.9.
> Add Django 4.0 support and update to test against Python 3.9

- setup.py
> Update Django 4 pin to allow versions under 4.1

- docs/releasenotes.md
- flags/__init__.py
Django 3.2 raises this warning:
```
/.../django/apps/registry.py:91: RemovedInDjango41Warning: 'flags' defines default_app_config = 'flags.apps.DjangoFlagsConfig'. Django now detects this configuration automatically. You can remove default_app_config.
app_config = AppConfig.create(entry)
```
This PR changes the `default_app_config` definition to be gated to Django < 3.2. This is the same solution as I’ve implemented in my packages e.g. https://github.com/adamchainz/django-linear-migrations/blob/bf8233983a408fb8366f004b0def374d9b65b01f/src/django_linear_migrations/__init__.py .
> Prevent RemovedInDjango41Warning

- .github/workflows/test.yml
- README.md
- tox.ini
In [consumerfinance.gov](https://github.com/cfpb/consumerfinance.gov/blob/main/.github/workflows/backend.yml#L87-L127), we use `diff-cover` to measure coverage of a set of changes against `main`, and fail if the changes are not 100% covered. 
This PR brings our use of `diff-cover` into Django-Flags, with the intention to replace our use of Coveralls, which has been frustrating since our switch to GitHub Actions. It does this by adding a `coverage` env to tox and adding that env to the `envlist`. This means a full run through of our test matrix with `tox` locally will lint, run our tests, and then report out the difference in combined test coverage from all the matrix runs. 
I've added a new job to the `test` workflow in GitHub actions that will run that tox env.
> Drop Coveralls in favor of coverage reported in GitHub Actions

- flags/conditions/conditions.py
- flags/tests/test_conditions_conditions.py
AnonymousUser does not always have the USERNAME_FIELD attribute (for example it does not have an "email" field).
This fixes the following stacktrace:
```
File "/usr/local/lib/python3.10/site-packages/flags/state.py", line 66, in flag_enabled
return flag_state(flag_name, **kwargs)
File "/usr/local/lib/python3.10/site-packages/flags/state.py", line 61, in flag_state
return _get_flag_state(flag_name, **kwargs)
File "/usr/local/lib/python3.10/site-packages/flags/state.py", line 13, in _get_flag_state
return flag.check_state(**kwargs)
File "/usr/local/lib/python3.10/site-packages/flags/sources.py", line 51, in check_state
checked_conditions = [(c, c.check(**kwargs)) for c in self.conditions]
File "/usr/local/lib/python3.10/site-packages/flags/sources.py", line 51, in <listcomp> …
```
> Anonymous users never match user conditions

- setup.py
Add two links to the sidebar on PyPI, to make it easier for folks to jump to the relevant pages. Example: https://pypi.org/project/django-htmx/ (PyPI adds the icons based on the link names).
> Add package links to PyPI

- .gitignore
These have names like `.coverage.<hostname>.<pid>.<random>`.
> Git ignore parallel coverage files

- docs/index.md
Hi, 
according to https://cfpb.github.io/django-flags/releasenotes/, Django 4.0 is supported since version 5.0.6, Django 4.1 since version 5.0.7 and Django 4.2 since version 5.0.13.
I thought it would be good to have that information also in the index.
Best, 
Diego
> add django 4.x to supported django versions

- flags/state.py
`FlagState.objects.create` calls `FlagState.save`, but this isn't necessary as the line below calls it after setting the right value. Avoiding this extra `save()` will speed up creating flags through `enable_flag` / `disable_flag`.
> Avoid double save in _set_flag_state

- docs/testing.md
- docs/usage.md
- mkdocs.yml
Document how flags can be toggled in tests
https://github.com/cfpb/django-flags/issues/121
> docs: document how flags can be toggled in tests

- .github/workflows/test.yml
- tox.ini
Repeat of #109 with the latest and greatest Python.
> Run linters on Python 3.12

- docs/usage.md
Link was returning a 404 because of missing 'django-flags' in the path.
> Corrected link to API State

- .github/workflows/test.yml
- docs/releasenotes.md
- setup.py
- tox.ini
New Django is coming!
Copied where to change from #110.
Python 3.10 is the minimum for Django 5.0: https://docs.djangoproject.com/en/5.0/releases/5.0/ , so needed to bump up testing to use it.
> Test on Django 5.0
